# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3f07586ba0ee886ca35c5f4d29bf86e871f96347aa41675fad4d8563d17b7d7b5c0c7e7bfa7cc3dc39e67a030d14c9dbf30cdd7f0eca85ceb609fe94b4c5a7

test:
  secret_key_base: 7ae7eda8127024d1621ced084294b21c30c2568c5bf1830d39a4fc816721a3193d6e8c6c781603638fe33971baa132c2a7440f4a35881da4798b47f68341e377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
